# Default values for init-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: postgres
  tag: 15-alpine
  pullPolicy: IfNotPresent

# The secret should contain: host, port, username, password, dbname
existingSecret: pgvector
existingSecretNamespace: llama-stack-rag

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
