apiVersion: v1
kind: Secret
metadata:
  name: ai-virtual-assistant-proxy
  labels:
    {{- include "ai-virtual-assistant.labels" . | nindent 4 }}
type: Opaque
stringData:
  session_secret: {{ .Values.sessionSecret.value | default (randAlphaNum 64) | quote }}
