# Default values for vectordb-ingestion-monitor
replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/openshift/tools
  tag: latest
  pullPolicy: IfNotPresent

monitor:
  name: ingestion-pipeline-monitor
  serviceAccount:
    create: true
    name: ingestion-pipeline-monitor
  rbac:
    create: true
    role:
      name: ingestion-pipeline-monitor
    roleBinding:
      name: ingestion-pipeline-monitor

llamastack:
  baseUrl: "http://llamastack.rag-llama-demo.svc.cluster.local:8321"

dsPipeline:
  url: "https://ds-pipeline-dspa.rag-llama-demo.svc.cluster.local:8888"

securityContext:
  runAsUser: 1000840000 