apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "init-db.fullname" . }}-schema
  labels:
    {{- include "init-db.labels" . | nindent 4 }}
data:
  schema.sql: |
    {{ .Files.Get "files/schema.sql" | nindent 4 }} 